const imageBaseUrl = process.env.RMU_MFE_ASSETS!;
export const defaultStrategicGameImage = `${imageBaseUrl}images/generic/strategic.png`;
export const defaultFactionImage = `${imageBaseUrl}images/avatars/avatar-001.png`;

export const getGenericImages = () => {
  return [
    `${imageBaseUrl}images/avatars/avatar-000.png`,
    `${imageBaseUrl}images/avatars/avatar-001.png`,
    `${imageBaseUrl}images/avatars/avatar-002.png`,
    `${imageBaseUrl}images/avatars/avatar-003.png`,
    `${imageBaseUrl}images/avatars/avatar-004.png`,
    `${imageBaseUrl}images/avatars/avatar-005.png`,
    `${imageBaseUrl}images/avatars/avatar-006.png`,
    `${imageBaseUrl}images/avatars/avatar-007.png`,
    `${imageBaseUrl}images/avatars/avatar-008.png`,
    `${imageBaseUrl}images/avatars/avatar-009.png`,
    `${imageBaseUrl}images/avatars/avatar-010.png`,
    `${imageBaseUrl}images/avatars/avatar-011.png`,
    `${imageBaseUrl}images/avatars/avatar-012.png`,
    `${imageBaseUrl}images/avatars/avatar-013.png`,
    `${imageBaseUrl}images/avatars/avatar-014.png`,
    `${imageBaseUrl}images/avatars/avatar-015.png`,
    `${imageBaseUrl}images/generic/strategic.png`,
    `${imageBaseUrl}images/generic/map.png`,
    `${imageBaseUrl}images/generic/tactical.png`,
    `${imageBaseUrl}images/generic/armor-shield.png`,
    `${imageBaseUrl}images/races/generic-dark-human-01.png`,
    `${imageBaseUrl}images/races/generic-desert-human-01.png`,
    `${imageBaseUrl}images/races/generic-dwarf-01.png`,
    `${imageBaseUrl}images/races/generic-east-human-01.png`,
    `${imageBaseUrl}images/races/generic-elf-01.png`,
    `${imageBaseUrl}images/races/generic-elf-02.png`,
    `${imageBaseUrl}images/races/generic-elf-03.png`,
    `${imageBaseUrl}images/races/generic-elf-04.png`,
    `${imageBaseUrl}images/races/generic-grey-elf-01.png`,
    `${imageBaseUrl}images/races/generic-halfling-01.png`,
    `${imageBaseUrl}images/races/generic-high-elf-01.png`,
    `${imageBaseUrl}images/races/generic-high-human-01.png`,
    `${imageBaseUrl}images/races/generic-high-orc-01.png`,
    `${imageBaseUrl}images/races/generic-horse-human-01.png`,
    `${imageBaseUrl}images/races/generic-human-01.png`,
    `${imageBaseUrl}images/races/generic-human-02.png`,
    `${imageBaseUrl}images/races/generic-human-03.png`,
    `${imageBaseUrl}images/races/generic-human-04.png`,
    `${imageBaseUrl}images/races/generic-human-05.png`,
    `${imageBaseUrl}images/races/generic-human-06.png`,
    `${imageBaseUrl}images/races/generic-human-07.png`,
    `${imageBaseUrl}images/races/generic-human-08.png`,
    `${imageBaseUrl}images/races/generic-lesser-orc-01.png`,
    `${imageBaseUrl}images/races/generic-orc-01.png`,
    `${imageBaseUrl}images/races/generic-orc-02.png`,
    `${imageBaseUrl}images/races/generic-orc-05.png`,
    `${imageBaseUrl}images/races/generic-troll-01.png`,
    `${imageBaseUrl}images/races/generic-troll-02.png`,
    `${imageBaseUrl}images/races/generic-war-troll-01.png`,
    `${imageBaseUrl}images/races/generic-wood-elf-01.png`,
    `${imageBaseUrl}images/races/generic-wood-elf-02.png`,
    `${imageBaseUrl}images/races/generic-wood-human-01.png`,
    `${imageBaseUrl}images/races/sauron.png`,
    `${imageBaseUrl}images/races/unknown.png`,
    `${imageBaseUrl}images/npcs/wolf.png`,
    `${imageBaseUrl}images/npcs/warg.png`,
    `${imageBaseUrl}images/npcs/bear.png`,
    `${imageBaseUrl}images/npcs/dog.png`,
    `${imageBaseUrl}images/npcs/unknown.png`,
  ];
};
